In [34]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

from sklearn.tree import DecisionTreeClassifier, plot_tree

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [2]:
df = pd.read_csv("drug200.csv")
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [4]:
df['Sex'].value_counts()

Sex
M    104
F     96
Name: count, dtype: int64

In [5]:
df['Sex'].replace({"M":1,"F":0},inplace =True)

In [8]:
df['BP'].value_counts()

BP
HIGH      77
LOW       64
NORMAL    59
Name: count, dtype: int64

In [13]:
df['BP'].replace({"HIGH":3,"LOW":2,'NORMAL':1},inplace =True)

In [10]:
df['Cholesterol'].value_counts()

Cholesterol
HIGH      103
NORMAL     97
Name: count, dtype: int64

In [14]:
df['Cholesterol'].replace({"HIGH":1,'NORMAL':1},inplace =True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    int64  
 2   BP           200 non-null    int64  
 3   Cholesterol  200 non-null    int64  
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(4), object(1)
memory usage: 9.5+ KB


In [22]:
x = df.drop('Drug',axis=1)
y = df['Drug']

x_train,x_test, y_train, y_test = train_test_split(x,y,random_state=1, stratify=y)

dt_clf = DecisionTreeClassifier(criterion = 'gini',random_state=1)
dt_clf.fit(x_train, y_train)

DecisionTreeClassifier(random_state=1)

In [23]:
acc_train = dt_clf.score(x_train,y_train)
acc_train


1.0

In [24]:
acc_test = dt_clf.score(x_test,y_test)
acc_test

0.94

In [25]:
plt.figure(figsize = (100,90))
tree = plot_tree(dt_clf, feature_names = list(x.columns),class_names=['drugY','drugX','drugA','drugC','drugB'],filled=True)
plt.savefig('DT_clf.png')

## training data evaluation

In [32]:
y_pred_train = dt_clf.predict(x_train)

cnf_matrix = confusion_matrix(y_pred_train,y_train)
print("Confusion matrix :\n",cnf_matrix)
print("*"*59)
Accuracy = accuracy_score(y_pred_train,y_train)
print("Accuracy score :",Accuracy)
print("*"*50)

clf_report = classification_report(y_pred_train,y_train)
print("Classififcation report :",clf_report)

Confusion matrix :
 [[17  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0 41  0]
 [ 0  0  0  0 68]]
***********************************************************
Accuracy score : 1.0
**************************************************
Classififcation report :               precision    recall  f1-score   support

       drugA       1.00      1.00      1.00        17
       drugB       1.00      1.00      1.00        12
       drugC       1.00      1.00      1.00        12
       drugX       1.00      1.00      1.00        41
       drugY       1.00      1.00      1.00        68

    accuracy                           1.00       150
   macro avg       1.00      1.00      1.00       150
weighted avg       1.00      1.00      1.00       150



## testing data evaluation

In [33]:
y_pred = dt_clf.predict(x_test)

cnf_matrix = confusion_matrix(y_pred,y_test)
print("Confusion matrix :\n",cnf_matrix)
print("*"*59)
Accuracy = accuracy_score(y_pred,y_test)
print("Accuracy score :",Accuracy)
print("*"*50)

clf_report = classification_report(y_pred,y_test)
print("Classififcation report :",clf_report)

Confusion matrix :
 [[ 6  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  3  2  0]
 [ 0  0  1 11  0]
 [ 0  0  0  0 23]]
***********************************************************
Accuracy score : 0.94
**************************************************
Classififcation report :               precision    recall  f1-score   support

       drugA       1.00      1.00      1.00         6
       drugB       1.00      1.00      1.00         4
       drugC       0.75      0.60      0.67         5
       drugX       0.85      0.92      0.88        12
       drugY       1.00      1.00      1.00        23

    accuracy                           0.94        50
   macro avg       0.92      0.90      0.91        50
weighted avg       0.94      0.94      0.94        50



## Pickle file

In [36]:
with open("Drug.pkl",'wb') as f:
    pickle.dump(dt_clf,f)

In [37]:
df.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')